name: Deploy to Live Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Live
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.GH_PAT }}  # use PAT for authentication
          port: ${{ secrets.PORT }}
          script: |
            git credential approve <<EOF
            protocol=https
            host=github.com
            username=${{ secrets.USER }}
            password=${{ secrets.GH_PAT }}
            EOF
            cd /home/***/public_html/fin
            git remote set-url origin https://github.com/atdheboshnjaku/NareKaltro.git
            git pull origin main
