name: Deploy to Live Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Live
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.GH_PAT }}  # use PAT for authentication
          port: ${{ secrets.PORT }}
          script: |
            cd /home/***/public_html/fin
            git -c http.extraheader="AUTHORIZATION: basic $(echo -n "${{ secrets.USER }}:${{ secrets.GH_PAT }}" | base64)" pull origin main
