name: Deploy to Live Site

on:
  push:
    branches:
      - main  # Trigger the action on push events to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Live
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST -p $PORT "export LC_ALL=C.UTF-8 && cd public_html/fin && git pull origin main"
